### ISSUE TITLE
Multi-cores error

### ISSUE THREAD

**Issue by lucasbonald** [josephlewis/leastcostpath#8]
I have been facing some issues when I try to run the code in parallel. I received this message below:

 lcp_network <- create_FETE_lcps (cost_surface = teste_cs,locations = loc,cost_distance = FALSE,parallel = TRUE,ncores = 11)
  |                                                  | 0 % ~calculating  Error in checkForRemoteErrors(val) : 
  11 nodes produced errors; first error: Invalid vertex name(s)

Obs:
I have a Xeon E5 2670 v3 CPU with 12 cores and 24 threads

**Comment by josephlewis** [comment]
Hi,

This error seems to be related to the igraph package. Please make sure that the gdistance version is >= 1.2-2

Are you able to provide a reproducible example where you get the error? 

Can you also try to calculate a single LCP using the same transition surface? This will allow me to better understand whether the problem is with the transition surface or the create_FETE function

Thank you.
